### ISSUE TITLE
Helm install error, and raven-agent-config is lost.

### ISSUE THREAD

**Issue by arctan90** [openyurtio/raven#101]
https://github.com/openyurtio/raven/blob/e5ad17d92d78ec266a3dcb31a3306e30b800c10a/charts/raven-agent/templates/config.yaml#L4

---
# error msg
Error from server (BadRequest): error when creating "cm.yaml": ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found f, error found in #10 byte of ...|node-ip":false,"vpn-|..., bigger context ...|{"apiVersion":"v1","data":{"forward-node-ip":false,"vpn-driver":"libreswan"},"kind":"ConfigMap",|...
## reason
Run helm template comes to
```yaml
# Source: raven-agent/templates/config.yaml
apiVersion: v1
data:
  vpn-driver: libreswan
  forward-node-ip: false
kind: ConfigMap
metadata:
  name: raven-agent-config
  namespace: kube-system
```
the ```forward-node-ip: false``` should be ```forward-node-ip: "false"```
---
# Suggestion
using quote in helm chart, and maybe some change in operator for this configuration.
```  forward-node-ip: {{ .Values.vpn.forwardNodeIP | quote }}```
